from pathlib import Path
import json
r=Path(__file__).resolve().parents[2];root=r/'examples/adventure'
engine=(root/'engine.js').read_text();default=json.loads((root/'prism.json').read_text());template=(root/'interface.html').read_text().replace('/*ENGINE*/',engine)
# Literal HTML is generated locally; user scenario strings are JSON encoded and rendered through textContent.
source='''"""\ntitle: STEM Adventure\ndescription: Render a deterministic text adventure with rooms, inventory, and exportable play records.\nversion: 0.2.1\n"""\nimport json\nfrom fastapi.responses import HTMLResponse\n\nDEFAULT_SCENARIO = '''+repr(default)+'''\nHTML_TEMPLATE = '''+repr(template)+'''\n\nclass Tools:\n    def render_stem_adventure(self, scenario_json: str = "") -> tuple:\n        """Open a playable text adventure inside chat. Leave scenario_json empty for Prism Laboratory.\n\n        :param scenario_json: Optional JSON scenario with title, introduction, start, rooms, actions, and goal_flags. No HTML or code.\n        """\n        if not isinstance(scenario_json, str):\n            raise ValueError("Scenario must be a JSON string.")\n        if len(scenario_json) > 50000:\n            raise ValueError("Scenario exceeds 50,000 characters.")\n        scenario = json.loads(scenario_json) if scenario_json.strip() else DEFAULT_SCENARIO\n        if not isinstance(scenario, dict):\n            raise ValueError("Scenario must be a JSON object.")\n        for field in ("title", "introduction", "start", "rooms", "actions", "goal_flags"):\n            if field not in scenario:\n                raise ValueError("Missing scenario field: " + field)\n        payload = json.dumps(scenario, ensure_ascii=True).replace("<", "\\\\u003c").replace(">", "\\\\u003e").replace("&", "\\\\u0026")\n        html = HTML_TEMPLATE.replace("/*SCENARIO*/", payload)\n        return HTMLResponse(content=html, headers={"Content-Disposition": "inline"}), {\n            "status": "rendered", "title": scenario["title"],\n            "description": "Interactive adventure with explicit action rules, inventory, and typed help, undo, restart, save, load, and discuss commands. Scenario validation runs before rendering and inside the game before play.",\n            "evaluation": "Ask the player to type discuss inside the game and send the resulting record before discussing their moves. Clicks inside the iframe are not automatically sent to the model.",\n            "persistence": "Type save to download a play record, then load to resume after chat reload.",\n        }\n'''
validation=(root/'validation.py').read_text()
source=source.replace('class Tools:',validation+'\n\nclass Tools:').replace('        payload = json.dumps', '        validate_scenario(scenario)\n        payload = json.dumps')
(r/'examples/tools/stem_adventure.py').write_text(source)
(root/'preview.html').write_text(template.replace('/*SCENARIO*/',json.dumps(default).replace('<','\\u003c')))
print('Generated native HTMLResponse tool and local preview.')
